name: Build (Ubuntu)

on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Build plugin for Windows (using docker)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Cache Docker layers
              id: cache-docker
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
                  restore-keys: |
                      ${{ runner.os }}-docker-

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build docker image
              run: |
                  export DOCKER_BUILDKIT=1
                  docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                               --cache-to=type=local,dest=/tmp/.buildx-cache \
                               -t ukcp-builder .

            - name: Run the build using the built image
              run: |
                  docker run -it ukcp-builder

            - name: Build plugin
              run: |
                  docker run -it ukcp-builder /bin/bash -c "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN -G Ninja -B build"
